server:
  port: 8081
spring:
  profiles:
    active: dev

---
spring:
 profiles: dev
server:
  port: 8080
debug: false
logging:
  file: springboot.LOG


---
spring:
 profiles: test

---
spring:
 profiles: prod
